FROM python:3.11-slim
WORKDIR /app
COPY ./app ./app
RUN pip install fastapi[all] uvicorn "sqlalchemy" "python-jose[cryptography]" "passlib[bcrypt]"
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]